# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.16.3

# Mod Properties
version=1.0.0
group=com.github.duskong.waystonemap
archives_base_name=Fast_Travel_Waypoints-Fabric-26.2

# Dependencies
fabric_api_version=0.161.0+26.2

xaeros_minimap_version_id=VlMbRW2O
xaeros_worldmap_version_id=q0Wvp46X
xaeros_lib_version_id=1.7.7
waystones_version_id=26.2.0.12
